dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
services:
- postgresql
before_script:
- psql -c 'create database frameworkeventstore;' -U postgres
- psql -c 'create database frameworksystem;' -U postgres
- psql -c "CREATE USER framework WITH PASSWORD 'framework';" -U postgres
addons:
  postgresql: '9.5'
  sonarcloud:
    organization: cjscommonplatform
    token:
      secure: P3NV1Pmf1AbqWnr/AYiTez8qVxeH+6Pv1T0pt5QgC0PJizQF3BQcThplDl1Kf5tmCfBPnC2WbHrBPB2ruzZPO1xt/hDBEWsSDgNhfg2A0lXxx6STcgknVCUb8PrrMU1H8lrw4CJZt32phyVn1ebwWJ+sKdUvn72j82NrAtUY5sJcwGbmF3QOO1mLRTXRnjIiEiH26ClPtIBPSm2bWPyxkbFsLZXp0X9AkC5/054F24suoOKLs1Co2HO8XPdsZLEBjGmiBowajMwTLuXh1642lCDqLxkpGc3F9gBH1CKqjsJ5jzM2VZbncc3uq4UgTs1RHU0ni2WoiUci7VtGb0uN/cvFJ2gncEoZuZaVmPt7YBd7B6a9AJcFztgA3C0IZjdYVuiSaNl6Z//+Cg14+8QAfmFeBIrnEQZrgU2LL4p24v9FkGNVcDJjVTZ7SndcYxZV2Ymo6Cwe4lXMxTqMzlV8DezTaYKDIx+BuoDWuutvR5gZB/wIHAps6O7FzWDonX6QEWk3VCZEqZ9UHu78kX1r63yMgavI+q+iKyoiFjeijXzothxSCXbKAakFnUIgAq2sz9iwRA1nBhoxF5nRIx6jhLIT+ZwAUN9NUb5htTUkrvQNA+g+bl9ry7Dp+0Pw1q6kkBeA9z47ilTu+Tmdl6q8/tKmcfobcvhf8OMoN6QM/jc=
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
- ln -sfT ${PWD}/target/travis-settings/mvnw mvnw
- ln -sft ${PWD} ${PWD}/target/travis-settings/.mvn
install: "${PWD}/target/travis-settings/java/install.sh -e -q -DexcludeGroupIds=uk.gov.justice.service,uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications: 
env:
  global:
  - PGPORT=5432
  - secure: ZdNM155db6QZN3MYeK+qfT7CUEk7ce0lc+kl1kIqsuMaQPa7UvRUCrBCKmh1/vaOBj1H2QTVSh/MOdvzc1TyvdV75hmDBUdtaIodbfENCEGYxp88F6Q4/daiwnVB29TGkxXSSfzt4X78wwE+RC19AqnXWkZBX/XQjbkKrf+kN4xOnJqLqmBV3L2tVi3pGZ4VQenkAyGJ2ZXUT2ln5oZXbnwQF2UW+NUDaiPAkN+GZm5dOO6ANuDKHgUMSMxS/XCDOy0AByqpdbCKUR45L1RWSPZWAnZDaBGiVRuKkhB90Z8keCoE8JWAdvu6TipEFnbE0GCoAO7iVGd37O7i995A0ufAOnrX6MqzcDp82kSgZ6e08fllABvu8c+nLsrFMpvYshZ1r+ok10mWUyWFrgWiCJihDnK/jXRhDIsq4bUwPBSbf3apv5Qf3orK8b5dLKngVO36lhBElQH+NVG51TBhsbYDXS3zBQYL57AQrcS6+AreY/qk5YmwOocfl4BWDAmuIlSlq+6t614XkyX8RbZY4R/TFtG4koXKb5a1rykaKv7dOjAgR4EyONi97hTTSJWzsB0YNq++vb2NiyOldtPkZxZlChkfjGd3perdW0kDRqxXVoZIDMwtIC+yzvv5O7/ozpmxX2fhsgVWmiGOMsWmo78UG+tghZc5A9+wQLq7LF0=
  - secure: IclkKXt0NwpzZrh93v4SogKKgXjP/PiVE7LsAEne2oMlJQu0lwnF1I+ap7yvefIB1YIOsT5NAo2TvWOsQGBhw5zygB6lvpugzCrCi7Y2qRkvFu04d1X8iDP11XtoNsoXFrpvk2sXWhsJG01ssAQ/wke/YgsJcKsf6nfPagF1rsrn8KXlEKtTOUBTYLD+eoMYA+3MypQFb7uHJ0TlBqqWJxu2mZR0A0Eg/nIwLvkuJSJ0Ee1GrObMIm+qSMhuno2ycHhq4bf6ahf5iYl/L7HMtNdRNy/cnlYJmggf9ph2au2sFISEe9ZDRyFec5y5jD9J5OUvWraXEwz6ezm+ci9rOv9WYYSlmwsqZhIEdp4up0BMwGfVsISMcv1irXyt+6gPfU/TbzKV3SJUyRGYRW0EfDb6LqFEEyJJxekxaTp/xieD30ldmiDOnNE64QplspHE3J9OlL0mFB5OAdX1tzWGVswPk9R1yKskD27TlaTQx8Ew7Lt85FHr74SIi/8ss2ftCKC9N6VhW5ZJfZvoktBogUoHo8zWlWKGPZUcLpfmYYZvc8C0Hg4z9LRwdajjuB4PjZIJwUhaUd8VqiPFwPBc5OOEaA9d1HJR8dxV1qbPOMk/AKO1n8HHLDnkHeKPt+vEyVQzi9FMSdvcdlUm4V+USKtjI3X3hAYoT9j8dq5K92Y=
